## docker-compose.yml  for CouchBase File
# Use root/example as user/password credentials
version: "3.8"
# network_mode: "overlay"

networks:
  cb:
    driver: deploy
services:
  master:
    image: arungupta/couchbase:latest
    deploy:
      replicas: 1
    environment:
      - TYPE=MASTER
    volumes:
      - db-data:/var/lib
    ports:
      - "8091:8091"
  #   - "8092:8092"
  #   - "8093:8093"
  #   - "8094:8094"
  #   - "11210:11210"
    networks:
      - overlay    
  worker:
    image: arungupta/couchbase:latest
    deploy:
      replicas: 1
    environment:
      - TYPE=WORKER
      - COUCHBASE=master.couchbase
      - AUTO_REBALANCE=false
    volumes:
      - db-data:/var/lib
    networks:
      - overlay
networks:
    overlay:
volumes:
    db-data: