## docker-compose.yml File
# Use root/example as user/password credentials
version: "3.8"

services:
  db:
    image: argungupta/couchbase:latest
    deploy:
      replicas: 1

    command: --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    environment:
      - MYSQL_ROOT_PASSWORD=giveYOwn
      - MYSQL_PASSWORD=ad123456 # MongoDB env, too.
      - MYSQL_USER=adminer
      - MYSQL_DATABASE=schule
    volumes:
      - ./MysqlDaten:/var/lib/mysql
    ports:
      - "8091:8091"
      - "8092:8092"
      - "8093:8093"
      - "8094:8094"
      - "11210:11210"
